/// Flutter icons PlayerIcon
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PlayerIcon
///      fonts:
///       - asset: fonts/PlayerIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PlayerIcon {
  PlayerIcon._();

  static const _kFontFam = 'PlayerIcon';
  static const String? _kFontPkg = null;

  static const IconData add_friends = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_post = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_vector = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData declaim_friends = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData accept_friends = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
