// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAatJoiW4pCg3fxHJvAzuWvrXfiMPda5AQ',
    appId: '1:924845558356:web:0eaca2749a75247fc4fbc1',
    messagingSenderId: '924845558356',
    projectId: 'players-clique',
    authDomain: 'players-clique.firebaseapp.com',
    storageBucket: 'players-clique.appspot.com',
    measurementId: 'G-2VTBH0P3YC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9GwoGUoqle2_rZ3tNVzc8ARj1rikOG_0',
    appId: '1:924845558356:android:84b623013c2ae57ac4fbc1',
    messagingSenderId: '924845558356',
    projectId: 'players-clique',
    storageBucket: 'players-clique.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-xAqvpNcToNyMkGuZ_Zbvky6xnYC3n0E',
    appId: '1:924845558356:ios:64fb7f159f907d90c4fbc1',
    messagingSenderId: '924845558356',
    projectId: 'players-clique',
    storageBucket: 'players-clique.appspot.com',
    iosBundleId: 'com.playersclique.playersClique',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-xAqvpNcToNyMkGuZ_Zbvky6xnYC3n0E',
    appId: '1:924845558356:ios:1bef8189a147e1c3c4fbc1',
    messagingSenderId: '924845558356',
    projectId: 'players-clique',
    storageBucket: 'players-clique.appspot.com',
    iosBundleId: 'com.playersclique.playersClique.RunnerTests',
  );
}
